blank_issues_enabled: false
contact_links:
  - name: Important update on GitHubIsss [select Open to know more]
    url: https://learn.microsoft.com/office/new-feedback
    about: We's transinging our feedback experience away from GitHub Issues. For more information, select Open.
